# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2 
updates:       # Enable version updates for pip
  - package-ecosystem: "pip"  # Specifies the package manager (Python)
    directory: "/authn-service"  # Path to the directory containing requirements.txt
    schedule:
      interval: "daily"  # Sets the update frequency to daily
    labels:
      - "triage-required"  # Adds a label indicating the PR needs triage
    assignees:
      - "dungeonstechlead"  # Assigns the PR to the tech lead
    reviewers:
      - "dragonsengineer"  # Requests a review from the engineer
    commit-message:
      prefix: "pip"  # Prefixes commit messages with 'pip',

